### ISSUE TITLE
Stuck/twitching at the top after fall

### ISSUE THREAD

**Issue by CritFlaw** [blay09/ForgivingVoid#12]
When going to the top, for a solid minute or so, you're just stuck at the top of the world before being able to fall. During this time, you're not able to even look around. This doesn't happen with only the mod installed, I'm just trying to figure out what mod it could be conflicting with. This is the modlist:

https://hastebin.com/avinowulos.coffeescript

**Comment by BlayTheNinth** [comment]
What version of Forgiving Void did this happen on?

**Comment by CritFlaw** [comment]
1.0.21

**Comment by BlayTheNinth** [comment]
Is this still an issue? It could be that you were just experiencing lots of lag at the time.

**Comment by CritFlaw** [comment]
I've since switched to using JED to do this.
