### ISSUE TITLE
1.12 FPS Hit

### ISSUE THREAD

**Issue by Zygus42** [blay09/ForgivingVoid#2]
ForgivingVoid_1.12-1.0.2
forge-1.12-14.21.1.2428-installer-win

Standing in a newly created vanilla world with no other mods and doing nothing costs about 100fps compared to not having your mod on.  I'm guessing that there's something you're checking for too often.

**Comment by BlayTheNinth** [comment]
There is no expensive operations happening until the mod actually teleports you back into the sky. Whatever lag you've been experiencing must have been due to external factors or different conditions (e.g. different world generation or options).

**Comment by Zygus42** [comment]
1.12 with no other mods installed and using Re-create to test on identical Creative map.  No movement on my part after spawn - just standing there looking in the same direction.  Only difference is your mod.  Tested multiple times to confirm.  There's nothing that I can see happening in the logs that would indicate why.

**Comment by BlayTheNinth** [comment]
Even though as I said the (very simple) code does not do anything that would get anywhere close to dropping FPS (especially not on the level you're describing), I decided to try and reproduce your issue.

Same Forge version, Vsync disabled, Maximum Framerate Unlimited. Same creative flat world with no structures generated. Framerate checked after initial world generation was done (approximately when the tutorial pops up). Both times, I got between 200 and 250, no matter if the mod was installed or not.

Finally, I also temporarily added profiling code:
```
[00] levels - 98.09%/98.09%
[01] |   New World - 99.82%/97.91%
[02] |   |   tick - 98.34%/96.28%
[03] |   |   |   mobSpawner - 48.38%/46.58%
[03] |   |   |   entities - 39.28%/37.82%
[04] |   |   |   |   regular - 98.86%/37.38%
[05] |   |   |   |   |   tick - 97.77%/36.55%
[06] |   |   |   |   |   |   travel - 35.48%/12.97%
[07] |   |   |   |   |   |   |   move - 53.81%/6.98%
[07] |   |   |   |   |   |   |   rest - 25.26%/3.28%
[08] |   |   |   |   |   |   |   |   unspecified - 99.80%/3.27%
[08] |   |   |   |   |   |   |   |   ForgivingVoidFall - 0.20%/0.01%
[07] |   |   |   |   |   |   |   unspecified - 20.93%/2.71%
```
The falling event handler takes 0.01% of the total processing time. It was likely being called by mobs spawning and slimes jumping. It's probably rounded up as well.

```
[00] connection - 1.65%/1.65%
[01] |   unspecified - 71.53%/1.18%
[01] |   travel - 17.65%/0.29%
[02] |   |   rest - 38.36%/0.11%
[02] |   |   unspecified - 35.93%/0.10%
[02] |   |   move - 25.70%/0.07%
[01] |   livingEntityBaseTick - 2.75%/0.05%
[01] |   entityBaseTick - 2.73%/0.05%
[02] |   |   unspecified - 89.83%/0.04%
[02] |   |   portal - 10.17%/0.00%
[01] |   ai - 2.36%/0.04%
[02] |   |   newAi - 52.12%/0.02%
[02] |   |   unspecified - 47.88%/0.02%
[01] |   push - 1.16%/0.02%
[01] |   keepAlive - 0.69%/0.01%
[01] |   headTurn - 0.68%/0.01%
[01] |   ForgivingVoidTick - 0.39%/0.01%
```
The actual tick handler takes 0.39% of the processing time the connection is taking (1.65%). Again, after rounding up, 0.01% of the total processing time.

After looking over the code, testing it out for myself and running it on a profiler, I can pretty confidently say my mod has nothing to do with your FPS issues.

If you want to try out the profiling yourself, [build 3 on my Jenkins](http://jenkins.blay09.net/job/Forgiving%20Void%201.12/3/) contains the code for Minecraft's [/debug command](https://minecraft.gamepedia.com/Commands#debug) to pick it up.

**Comment by Zygus42** [comment]
Retested on flatworld with no structures – same issue.

These are my graphics options – my computer can handle substantially better ones, but am designing a 1.12 mod pack for a small server, and some of our players have old computers, so I test on low settings.

[cid:image003.jpg@01D30AE6.2467BAD0]


Thinking maybe it’s the java arguments instead of graphics.  My JVM arguments are:
-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M

For the server I typically use ones more like:
-Xmx4G -Xms4G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=45 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts
Although I keep playing with these and haven’t gotten as far as testing this build for a server.


Would love to know what’s causing this, as only a few mods are doing something along these lines, while the rest seem to be fine.

**Comment by BlayTheNinth** [comment]
I can't give you support for general performance problems. It sounded like it was only my mod causing issues initially, but if you're experiencing the same thing with other mods, it just solidifies the belief that it's an issue on your end, not the mod's end.

If you have concerns about your JVM arguments I suggest checking out this post by cpw:
https://www.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/
