### ISSUE TITLE
Mods repost authorization request

### ISSUE THREAD

**Issue by Aemande123** [blay09/ForgivingVoid#22]
Hello there
Your mods are great!!!
can I move your mods to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China

I will not provide download sources other than Curseforge
and highlight your Patreon.

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

**Comment by BlayTheNinth** [comment]
My mods are either licensed MIT, GPL or Public Domain, all of which allow redistribution as long as no attempts are made to obscure the original author's credit.

![license](https://user-images.githubusercontent.com/1933180/73073229-30fc4d80-3eb7-11ea-82b5-a478735e6830.png)

You can see the license on the project page of the mod.

**Comment by Aemande123** [comment]
> My mods are either licensed MIT, GPL or Public Domain, all of which allow redistribution as long as no attempts are made to obscure the original author's credit.
> 
> ![license](https://user-images.githubusercontent.com/1933180/73073229-30fc4d80-3eb7-11ea-82b5-a478735e6830.png)
> 
> You can see the license on the project page of the mod.

Well, thank you very much
