### ISSUE TITLE
Aether+Cubic Chunks support

### ISSUE THREAD

**Issue by nodogsleft** [blay09/ForgivingVoid#23]
As of now, both mods work individually as intended with Forgiving Void. However, together, they cause one issue. When falling out of the Aether, the mod is coded to send you to y=256, regardless of the terrain Cubic Chunks generates at y=256 and above. With Forgiving Void, I've somewhat fixed the problem by setting the teleport at y=0. While this works most of the time, occasionally the Aether will still manage teleport you to the overworld. Any solutions?

**Comment by BlayTheNinth** [comment]
I'm not sure I fully understand the issue, but this sounds like something Aether would have to fix or make configurable.

**Comment by nodogsleft** [comment]
I think efforts on Aether stopped with a partnership a long while ago. I appreciate your response, however. I'll close this, judging that it would have to be on Aether's end.
