### ISSUE TITLE
Death is not always prevented despite having full health

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/ForgivingVoid#30]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.9

### Mod Version

6.0.1

### Describe the Issue

Sometimes, the player will die after falling through the void and landing even though they had enough health to survive.

Couldn't figure out a pattern to this yet, it seems very random.

**Comment by ghost** [comment]
Hello, why not giving the player high effects for a short period of time? 
(Healing, Resistance, Slow Falling, etc)
I think this should fix this issue - even if it's not the most elegant way for now.

**Comment by BlayTheNinth** [comment]
Closing since there's not been any other reports or reproduction on newer versions.
