### ISSUE TITLE
Specify exact Y level to teleport to and from?

### ISSUE THREAD

**Issue by Aceplante** [blay09/ForgivingVoid#36]
I would like to teleport if below -80 in the overworld, to y600 in the nether. I would like to teleport to y-80 in the overworld if above y600 in the nether. That does not seem to be possible unless I missed something. The only options are air (which brings you to the top of the world), ground (which, to my understanding, brings you to the surface of the world), and cave (which puts you in the first cave it finds from the bottom of the world). I want to always be under or above the world. Being magically placed in a cave doesnt make sense to me.

**Comment by BlayTheNinth** [comment]
I don't know where you got those options from, but Forgiving Void doesn't do any of that. I think you got the wrong mod.

**Comment by Aceplante** [comment]
hm, i think it was forgiving world. sorry about that
