### ISSUE TITLE
Stuck in the top of the Nether

### ISSUE THREAD

**Issue by SigmaFlame** [blay09/ForgivingVoid#37]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Mod Version

forgivingvoid-forge-1.19-7.0.0

### Balm Version

balm-forge-1.19.2-4.5.7

### Describe the Issue

When you fall in the void inside the nether, you spawn on the top of the nether.
The mod DOES NOT teleport you to the overworld, so you are stuck.
Tested with only your mod and Balm.

### Logs

There is no log for that

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No

**Comment by BlayTheNinth** [comment]
This is working as intended, Forgiving Void does not do any cross-dimensional travel.

You can set `triggerInNether` to `false` to disable teleportation in the Nether.
