### ISSUE TITLE
what does target at distance below do

### ISSUE THREAD

**Issue by inikishev** [blay09/ForgivingVoid#39]

**Comment by BlayTheNinth** [comment]
**trigger**AtDistanceBelow: `The distance to the minimum y level at which Forgiving Void should forgive the player and send them towards the sky.`

**Comment by inikishev** [comment]
> **trigger**AtDistanceBelow: `The distance to the minimum y level at which Forgiving Void should forgive the player and send them towards the sky.`

so if I jump from lets say y=100 and its set to 36 it won't work?
