### ISSUE TITLE
Died in the void

### ISSUE THREAD

**Issue by Collier21** [blay09/ForgivingVoid#42]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11-1.21

### Mod Version

1.21

### Balm Version

1.21-21.011

### Describe the Issue

The mod works great in any single-player game I've played in and I haven't had any issues. However, the first time I'm in my multiplayer server with my friends and I fall into the void, I keep dying. It's like the mod isn't even there. PLEASE HELP! I don't know if this mod works on only single-player worlds and doesn't on multiplayer servers or what but when I died I was very caught off guard because I had tested it out previously in my single-player world and it worked. And yes, my friend and I have the current version of this mod, and balm, if that clears anything up. I would love to incorporate this mod into my server so any help would be appreciated, Thanks!

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

I'm using iris shaders and a few resource packs but that's it.

**Comment by BlayTheNinth** [comment]
Please provide the full logs. You can find the logs in the `logs` directory of the server. Most of the time `latest.log` is the correct file (unless the crash or issue happened during an earlier run).

Logs can be uploaded here by dragging the file into the comment field, or you can post them on a site like https://gist.github.com/ or https://pastebin.com/. Make sure they are set to be `public` (or unlisted) and to `never expire`.
