### ISSUE TITLE
Dying on Fall with Absorption Hearts

### ISSUE THREAD

**Issue by sophienix** [blay09/ForgivingVoid#43]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

my version 47.3.0 server version 47.2.23

### Mod Version

10.0.1

### Balm Version

7.3.7

### Describe the Issue

when i have absorption hearts it kills when landing. note versions are different due to custom pack and using a premade server

### Logs

https://mclo.gs/Uqbb1C9

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

there is none on server but in-game i have modern fix

**Comment by BlayTheNinth** [comment]
Could not reproduce. With full health and 4 absorption hearts, I survived with 0.5 hearts. With 4.5 real hearts and 6 absorption hearts, I survived with 1 heart, i.e. as expected.

**Comment by sophienix** [comment]
werid might be my modpack then i uploaded it to https://legacy.curseforge.com/minecraft/modpacks/open-maid-skyblock/files

**Comment by BlayTheNinth** [comment]
Closing for now until there is more reports to create a minimal reproduction case.
