### ISSUE TITLE
Weirdness When Falling In Water

### ISSUE THREAD

**Issue by TheLimePixel** [blay09/ForgivingVoid#7]
This has been an issue for a long time and so I don't know why I'm reporting this now. Basically, whenever a player falls through the void and into water they obviously don't take damage. They do however take damage when they get out of it. I understand that the damage you take after falling through the void isn't fall damage and that's what causes this, but gameplay-wise this behavior makes no sense.

**Comment by Thyriel** [comment]
I was about to report the same problem here.
How about you add an option to just disable your mods damaging mechanic completely ? This way (with that option enabled in config) you would always die if you fall through the void and don't manage to hit water (or need to have something to mititage the falling damage), but at least you don't loose all items as you only die when you manage to hit your platform/island
